services:

  postgres:
    image: postgres:15
    container_name: payment_postgres
    restart: always
    environment:
      POSTGRES_DB: idempotent_payment_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: payment_adminer
    restart: always
    ports:
      - "8081:8080"

  app:
    build: .
    container_name: payment_app
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/idempotent_payment_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - "8080:8080"

volumes:
  pg_data: